# Generated by Django 5.0.7 on 2024-07-16 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_menu_item_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="item_item",
            new_name="item_category",
        ),
    ]
