# Generated by Django 5.0.7 on 2024-07-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_menu_menu_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="item_item",
            field=models.CharField(default="entree", max_length=200),
        ),
    ]
